version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  static_files: index.html
  upload: index.html
